//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class group
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public group()
        {
            this.group_members = new HashSet<group_members>();
            this.pictures = new HashSet<picture>();
        }
    
        public int group_id { get; set; }
        public string group_name { get; set; }
        public int group_manager_id { get; set; }
        public int price_perPerson { get; set; }
        public int price_perGroup { get; set; }
        public System.DateTime dateEvent { get; set; }
        public System.DateTime Last_Date_Registration { get; set; }
        public string address_event { get; set; }
        public bool is_active { get; set; }
        public string describe { get; set; }
        public Nullable<int> num_Participants { get; set; }
        public int category_id { get; set; }
    
        public virtual category category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<group_members> group_members { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<picture> pictures { get; set; }
    }
}
