//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class project_group_tami_and_giliEntities : DbContext
    {
        public project_group_tami_and_giliEntities()
            : base("name=project_group_tami_and_giliEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bank> banks { get; set; }
        public virtual DbSet<bank_details> bank_details { get; set; }
        public virtual DbSet<branch> branches { get; set; }
        public virtual DbSet<category> categories { get; set; }
        public virtual DbSet<group_members> group_members { get; set; }
        public virtual DbSet<group> groups { get; set; }
        public virtual DbSet<picture> pictures { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
